-- file: 0001.update-timestamps.sql

ALTER TABLE userPosts MODIFY time TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE userPosts ADD updated_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
    
ALTER TABLE userPostComments MODIFY time TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE userPostComments ADD updated_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE projectPosts MODIFY time TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE projectPosts ADD updated_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
    
ALTER TABLE projectPostComments	MODIFY time TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE projectPostComments ADD updated_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;